### ISSUE TITLE
creating the account from within the desktop-client.

### ISSUE THREAD

**Issue by shirishag75** [kontalk/desktopclient-java#10]
Hi all, 
While I'm intrigued by the possibilities that kontalk provides, it still needs the android-client for having an account. It would be best if this could be done within the existing desktop client rather than using something else. 

I did check the FAQ and it is also silent on the topic, look forward to have some sort of CLI or something to create an account as well. 

You could look at yowsup-cli as an inspiration for making a similar tool.

**Comment by abika** [comment]
well, Kontalk is primarily a network for mobile IM (e.g. the Kontalk-address is created from the phone number). And connecting to standard XMPP clients/server is planned for the future, so there is actually no need for using Kontalk without a mobile phone.

But its true that moving the user key from your phone manually to the pc is user unfriendly. The key could be transferred by the server secured with a password or authentication ID. However, this requires work on the Android client and server and I assume @daniele-athome has alreay a lot more important things to do.
