### ISSUE TITLE
Some received messages are not displayed in the chat window

### ISSUE THREAD

**Issue by abenthy** [kontalk/desktopclient-java#100]
I have the problem that some received messages don't appear in the chat window in the desktop client. The message are recevied by the client and properly saved in the `kontalk_db.sqlite` file, but left out in the chat window.

This happens when several messages arrive with the same timestamp value in the `date` field but different values in the `server_date` field (some of my messages have`server_date=NULL`). So this can be tested by sending a lot of messages in a short amount of time to a client connected with the java client. The other client should be an android client. I will provide screenshots and log files as soon as I have time.

### Additional information
Kontalk Desktop version: v.3.1.2
Operating System: OSX 10.11.6 El Capitan
Java version: 8 Update 112 (Build 1.8.0_112-b16)

**Comment by abika** [comment]
Thanks for reporting. Got it already.

(100 issues, yeah!)
