### ISSUE TITLE
accept and block are one to much

### ISSUE THREAD

**Issue by ecxod** [kontalk/desktopclient-java#101]
### Additional information
Kontalk Desktop version: all versions
Operating System: all systems

It is not necessary to use both, accept and block.
it enough if you offer the possibility to block somebody, there is no need to accept the opposite part.
if two people install kontalk they should be able to instantly communicate.
Sometimes I just want to say HEY and not necessarily to add him.
if its a bad guy I can block him its enough

**Comment by daniele-athome** [comment]
I have to disagree. The Internet is a dangerous and confusing place. I can present you with several abuse cases, but I'll name just one: spam.
