### ISSUE TITLE
Control kontalk's desktopclient-java by sending terminal commands?

### ISSUE THREAD

**Issue by arielenter** [kontalk/desktopclient-java#107]
Is there a way to control kontalk's desktopclient-java from terminal? Some times I want to custom kontalk's desktopclient-java behavior to something I think won't be necessary for all it's users and asking for such feature is not relevant, and if there were a way to control kontalk's desktopclient-java from terminal, for instance to sent it a connect and disconnect signal, I could write a bash.

For instance, I know it's a known issue, but sometimes the desktopclient gets a message and the android version on a cellphone using data don't because it may lose it's connection for what ever reason and it never gets the message. This wouldn't be a problem for me if I could make a script that disconnects the desktopclient when the computer locks its screen when it's not being use for a while. I could create a very easy script for that. Right now the only way I know I could do it is to close desktopclient and reopen it when I unlock the screen, which is not ideal. I suppose I could connect and disconnect the computer from the network all together xD? Either ways are awful in mi opinions.

Many GNU/Linux programs have a way to send them parameters in terminal when they are executed. Is there a list of orders or parameters that could be send to the desktopclient like wise?

Thank you.

### Additional information
Kontalk Desktop version: KontalkDesktop-3.1.2
Operating System: GNU/Linux Trisquel

**Comment by arielenter** [comment]
Now that I think I little more, there is probably a way to target desktopclient-java and block its connection. But having list of terminal commands for desktopclient-java would be awesome never the less.

**Comment by daniele-athome** [comment]
I'm sorry there is no such feature at the moment. We believe the proper way of addressing this would be implementing message sync among devices (so you receive all messages on all your devices), which is an open issue that we plan to address this year.
