### ISSUE TITLE
latest binary version does not connect to server

### ISSUE THREAD

**Issue by freddii** [kontalk/desktopclient-java#112]
Kontalk Desktop version: 3.1.2
Operating System: Debian Linux
Desktop Environment:  xfce

Latest release https://github.com/kontalk/desktopclient-java/releases/download/v3.1.2/KontalkDesktop-3.1.2.zip does not connect to server.

**Comment by daniele-athome** [comment]
Thanks for reporting. I've just tried 3.1.2 and it's connecting successfully. Would you mind sending me a log to the devteam address please?

**Comment by freddii** [comment]
Send the log to devteam.
The only solution is to compile it myself like below:

```
mkdir -p /home/$USER/programs_setup/kontalk_setup
cd  /home/$USER/programs_setup/kontalk_setup
git clone https://github.com/kontalk/desktopclient-java.git
cd /home/$USER/programs_setup/kontalk_setup/desktopclient-java
git submodule update --init
cd /home/$USER/programs_setup/kontalk_setup/desktopclient-java && ./gradlew -Dorg.gradle.java.home=/usr/lib/jvm/java-8-openjdk-amd64/ run
```

**Comment by daniele-athome** [comment]
I saw the log, thanks. I see you ran a plain "java" command, what is the JDK you were using for that?

**Comment by freddii** [comment]
$ java -version
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment (build 11.0.2+9-Ubuntu-3ubuntu118.04.3)
OpenJDK 64-Bit Server VM (build 11.0.2+9-Ubuntu-3ubuntu118.04.3, mixed mode, sharing)

**Comment by daniele-athome** [comment]
Can you try with Java 8 please? I see you use it when you manually build the app.

**Comment by freddii** [comment]
yes that was causing the problem.

running it with java 8 instead of my system default java 11 works.

/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -jar /home/$USER/programs_setup/kontalk_setup/KontalkDesktop-3.1.2/KontalkDesktopApp.jar

**Comment by daniele-athome** [comment]
Good! I've opened #113 for supporting latest Java.
