### ISSUE TITLE
Thread backroundcolor per user

### ISSUE THREAD

**Issue by webratte** [kontalk/desktopclient-java#14]
In issue #13 you talk about different Pics for different threds.
I think this would be too heavy.
But a simple color for different users would be a good idea.

So I can fast see whats the thread of my wife and so on.

**Comment by abika** [comment]
Note to myself: pics, colors, whatever... need an additional db field for each thread with JSON content

**Comment by abika** [comment]
finally done. You can set a custom background color (with gradient) for each thread. Dunno, I'm not that good with design. Looks like this:

![custom_bg](https://cloud.githubusercontent.com/assets/1074117/6785031/7db467e4-d183-11e4-9ebc-8873b8ce27a5.png)

**Comment by daniele-athome** [comment]
Nice stuff! :+1:
