### ISSUE TITLE
Encoding issues on Windows

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/desktopclient-java#15]
I hate Windows but, you know... friends :-)

Screenshot shows exchanging messages between me (Android) and my friend (Windows).
This happens for both directions (I see encoding artifacts on my Android and he sees artifacts on the desktop client).

As a rule: always use UTF-8 (but I think you know that already).

![kontalk-desktop-encoding](https://cloud.githubusercontent.com/assets/3763726/6651752/ab67bb5a-ca53-11e4-9f60-39cd0b92f3cf.png)

**Comment by abika** [comment]
> As a rule: always use UTF-8 (but I think you know that already).

* knowing: yes
* keep that in mind while coding: no

But I'm not the only one:) 

Review and merge to master as desired...

**Comment by daniele-athome** [comment]
Oops :-)

**Comment by daniele-athome** [comment]
Merged, thank you. I'll keep the develop branch for these kind of stuff.
I'll leave closing of this issue to you since I don't know if you need to make other modifications to the desktop client about this.

**Comment by Manizuca** [comment]
I still have problems with the coding in windows

![screenshot](https://cloud.githubusercontent.com/assets/6548848/7974318/8c396a12-0a36-11e5-90d6-d32d0ace9bec.jpg)

in the image im sending a message to myself and receiving it. it looks fine in my phone but weird in the desktop client.
the binary code for to outgoing message is

>c3 a1 c3 a9 c3 ad c3 b3 c3 ba

and the incoming one
>c3 **83 c2** a1 c3 **83 c2** a9 c3 **83 c2** ad c3 **83 c2** b3 c3 **83 c2** ba

Using v3.0beta2

**Comment by abika** [comment]
yes, its happening again on Windows, I'll investigate...
