### ISSUE TITLE
Installer/Uninstaller

### ISSUE THREAD

**Issue by webratte** [kontalk/desktopclient-java#16]
Later - if you start to release stable versions to public is would be good if there is a Installer. 

Espacially for Win and OSX.
I think for many users it's not easy to handle ZIP Files and start the right file.
A installer should extract the ZIP file and create some Icons (Desktop, Menu)
And the Uninstaller of course should remove all the installed stuff.

**Comment by daniele-athome** [comment]
I have some experience in Debian packaging, I could make a package and try to push it to experimental. Maybe now that I'm a FSFE member they will consider me eheheh but I don't think they'll accept betas :-(

**Comment by abika** [comment]
yes, the ordinary user will expect that.
* Windows: I will look into NSIS (yeah, scripting)
* Linux: a Debian package would be great, I can also add an AUR package for Arch. But this can wait until stable release, Linux guys are known to be capable of extracting a zip and click on file.
* Mac: no idea. But I heard Steve Jobs is dead, anyway

**Comment by abika** [comment]
The next release will include a Windows installer exe. For demanding or providing installer/packages for other platforms open additional issues.
