### ISSUE TITLE
Remove binary dependencies

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/desktopclient-java#22]
You knew this day would come @abika didn't you? :-)

**Comment by abika** [comment]
meeh, is this really necessary?

**Comment by daniele-athome** [comment]
What if I offer myself to do it? :P
Actually I was thinking of switching to Maven or Gradle to ease such a task... is it possible with ant by the way?

By the way: why ant?

**Comment by abika** [comment]
> By the way: why ant?

cause it provides everything that I need right now, and its kind of standard (well, at least everybody has it).

I played with Gradle now a bit and although its powerful and (more or less) easy to use - at the same time - I really don't see any benefit from switching to it(?)

**Comment by Flowdalic** [comment]
> I really don't see any benefit from switching to it(?)

Isn't this bug about removing binary dependencies? The benefit is not having them :) Correct me if I'm wrong, but with using plain ant, you can't get rid of them.

Build systems which support fetching maven dependencies include: Ivy, Maven and Gradle. And if you don't want to "programm" you build system using XML (like me), then the only option, from the three previously mentioned one, is Gradle. But I'm happy as long the binaries are removed. :)

**Comment by daniele-athome** [comment]
I'd also like to use one single tool among all of the project, however the server part is maven while Android app is gradle, so... 
The most interesting part is about removing binary dependencies. It will make testing and distribution easier (if we want to enter e.g. Debian I don't think they will be happy to see ant with some prepackaged jars :-)

**Comment by abika** [comment]
Y, I admit I don't get the "binary dependency" stuff. Doesn't matter what build tool is used, everything that's done at build time is using jars as deps for my own project. The difference is only whether the jars are included in my project or downloaded in some external local repo (~.gradle or ~.m2) on demand. Really compiling every 3rdparty lib at build time is very uncommon in Java and also hard to accomplish. I'm I wrong?

> I'd also like to use one single tool among all of the project, however the server part is maven while Android app is gradle, so... 

Gradle is fine as it has inbuild support for Maven (and Ant btw). Actually JCenter used for the Android app is nothing more than a different Maven repo as far as I know.

**Comment by daniele-athome** [comment]
Compiling dependencies? God no :-) I was talking about removing the jars from git and use a system to autodownload them at build time. Instead of writing an ad-hoc script full of wgets, use a build system that supports this way of doing things would really help.

**Comment by abika** [comment]
There is one jar left which is not in any maven repo. Guess this can be closed.

**Comment by daniele-athome** [comment]
I see that easyogg.jar... it's kinda odd leaving it just there... is there any alternative library? e.g. http://www.jcraft.com/jorbis/

**Comment by abika** [comment]
It's only a convenience class for playing OGGs using jorbis, one file. I will add it directly

**Comment by daniele-athome** [comment]
:+1:
