### ISSUE TITLE
Background image

### ISSUE THREAD

**Issue by abika** [kontalk/desktopclient-java#24]
Imho the currently used self-made background image doesn't really look that good. A simple, modern looking one - that is inconspicuous - would be good. Or just a plain colour.

However, I'm not a design expert, so any suggestions/opinions on that? @webratte , @daniele-athome maybe you can help plz.

**Comment by daniele-athome** [comment]
You're asking the wrong man :-) but @acappelli might get in contact with our application icon creator.

**Comment by abika** [comment]
No default background image for now (until we find a better one)
