### ISSUE TITLE
Open conversation with single click

### ISSUE THREAD

**Issue by webratte** [kontalk/desktopclient-java#29]
If I click on a contact it's marked.
But I need a doubleclick to open the conversation for this contact.
Very often I send messages to wrong receiver because I only clicked only single.

Or if contactlist is open there should no conversation shown because on this way it's impossible to send to wrong receivers.

I hope you will understand what I mean.

**Comment by abika** [comment]
I understand and you're totally right.
> Or if contactlist is open there should no conversation shown because on this way it's impossible to send to wrong receivers.

For now this is done, best/quickest solution. But you gave me another idea: the "Edit user" dialog can be shown in the thread view instead, with more/detailed information. The space is empty now anyway.
