### ISSUE TITLE
Allow using JDK 7 ?

### ISSUE THREAD

**Issue by strk** [kontalk/desktopclient-java#31]
JDK version 8 is not easily available on free software platforms (I've understood that's due to parts of the classes in the standard library being not available as free software).

It would be nice if the kontalk desktop client could be installed on a purely free operating system.

**Comment by daniele-athome** [comment]
I don't remember using anything JDK 8 specific in client-common-java. What about you @abika?

**Comment by strk** [comment]
Are these JDK8 specific ?
```
/usr/src/kontalk/desktopclient-java/src/main/java/org/kontalk/Kontalk.java:28: error: cannot find symbol
import java.util.Optional;
                ^
  symbol:   class Optional
  location: package java.util
```

**Comment by abika** [comment]
Yes, `Optional` is new in Java 8.

No new language features are used, the byte code version is for Java 7 (that's why the client can be started with Java 7, a warning message appears though).

Sorry, but Java 8 is already over one year old and support for 7 is discontinued.

> JDK version 8 is not easily available on free software platforms

Huh, what distro? I'm developing with OpenJDK8, its not available for you?

**Comment by strk** [comment]
Ubuntu 14.04.2 LTS
```
apt-cache search openjdk | grep 8 # no hits
apt-cache search openjdk | grep 7 | wc -l # 14 hits
apt-cache search openjdk | grep 6 | wc -l # 14 hits
```
```

**Comment by abika** [comment]
wow, Ubuntu is really way behind. Sorry again, but you either have to compile from source or update to at least 14.10.

**Comment by daniele-athome** [comment]
Mmm... 14.04.2 will be supported until August 2016. It could put off a lot of users, what do you think @abika? Could it be worth the effort?

**Comment by abika** [comment]
I don't know. 14.04 LTS will have support until 2019. And Canonical will provide only jre7 until then, which doesn't get security fixes anymore? Really?

**Comment by daniele-athome** [comment]
I think they'll provide a backport sooner or later... won't they?

**Comment by abika** [comment]
whatever...

**Comment by abika** [comment]
Changed my mind again, won't do this.

To be honest: I could easily make the code work with Java7. But first, I don't wanna get stuck in an outdated framework. And second, I don't want to support irresponsible package update practices.

Have a look at https://bugs.launchpad.net/ubuntu/+source/openjdk-8/+bug/1341628
> This bug affects 358 people
