### ISSUE TITLE
Could not find property 'smackVersion' on project ':client-common-java'

### ISSUE THREAD

**Issue by strk** [kontalk/desktopclient-java#32]
Building the code fails, both with /usr/bin/gradle and ./gradlew.
In both cases the error is:
```
FAILURE: Build failed with an exception.

* Where:
Build file '/usr/src/kontalk/desktopclient-java/build.gradle' line: 19

* What went wrong:
A problem occurred evaluating root project 'kontalk_java'.
> Could not find property 'smackVersion' on project ':client-common-java'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

```

**Comment by strk** [comment]
For the record, I'm on an Ubuntu 14.04.2 LTS.

**Comment by strk** [comment]
May be related to #31 (JDK7, but I don't know)

**Comment by abika** [comment]
Git submodule is missing, see [how-can-i-compile-the-code](https://github.com/kontalk/desktopclient-java/wiki#how-can-i-compile-the-code).

I'll edit the front page README soon

**Comment by strk** [comment]
Ah! Yep, I missed the submodule part. Could "gradle" not take care of erroring out with a meaningful error message, in that case ?

**Comment by abika** [comment]
Yep, done.

**Comment by Romascu** [comment]
Hello, could someone please provide more exact details about this issue?

I am using the latest Android Studio version, downloaded Kontalk android version - tried to build and got the same error as strk.

Exact steps would be appreciated (from download to successful build) so i can see what i'm missing.

I did try the commands in the "how to compile guide"

Would really appreciate it, thanks a lot.
