### ISSUE TITLE
[Windows] - Last badge message error

### ISSUE THREAD

**Issue by M4v3r1cK87** [kontalk/desktopclient-java#35]
Hello,
during a chat session, the server goes down. The desktop show correctly the error badge for connection timed-out, but, when the server goes up and retry to connect to the server, the connection is backed up but the error badge show always "Can't login to server".

![last_badge](https://cloud.githubusercontent.com/assets/11871250/8678103/f26d1d24-2a52-11e5-9b53-a8b2f16a1886.PNG)

**Comment by abika** [comment]
can you provide the log for that? It's possible that there were 2 connection attempts after connection lost: First failed, second with success. So, the connection is actually there and the error message is a leftover.

**Comment by M4v3r1cK87** [comment]
Sorry but if @daniele-athome don't kill the server is not possible !!

**Comment by daniele-athome** [comment]
@M4v3r1cK87 can you try to kill your connection abruptly? E.g. disconnect your LAN cable.

**Comment by M4v3r1cK87** [comment]
OK, I goes down my ethernet link and if I try to reconnect the application, any attempt to reconnect, the application displays a badge without deleting the old ones, and when the application go online and connected not delete the old badges:
![connecting](https://cloud.githubusercontent.com/assets/11871250/8694384/ce2040fe-2ade-11e5-83f5-b132bd33e5ca.PNG)

**Comment by abika** [comment]
ok, so the simple solution here is to close the error messages after connecting

**Comment by abika** [comment]
closed with b47d3702bed2bb58a1675abb685f17c321a4df70
