### ISSUE TITLE
[Windows] - Missing notification for received message

### ISSUE THREAD

**Issue by M4v3r1cK87** [kontalk/desktopclient-java#37]
Seems to missing the notification for the received message. 
Can you implement ballon popup notification in the system tray or something else (for example blink kontalk icon if the program is open or if is closed, appear a ballon popup for the kontalk icon in the system tray)?

**Comment by abika** [comment]
you'll see a modified tray icon on new message arrivals. This shouldn't be too intrusive but enough 	noticeable

**Comment by freddii** [comment]
it would be nice to be able to activate to see the actually message as a popup like:
/usr/bin/notify-send --icon=$HOME/.local/share/icons/kontalk.png "hello"
