### ISSUE TITLE
[Windows] - Emoji not visible, strange characters in chat

### ISSUE THREAD

**Issue by M4v3r1cK87** [kontalk/desktopclient-java#38]
It seems the chat is not supporting the Emoji, can you fix this ? Expecially because in chat is visible a strange character for any emoji.

![emoji missing](https://cloud.githubusercontent.com/assets/11871250/8693197/979288a2-2ad5-11e5-8141-e39df43a1325.PNG)

**Comment by abika** [comment]
duplicate of #20
