### ISSUE TITLE
[Windows] - Desktop Client seems to auto-accept chat requests

### ISSUE THREAD

**Issue by M4v3r1cK87** [kontalk/desktopclient-java#41]
It seems the Desktop client auto-accepting key changes.

I write a message to my friend that show in the contacts list, i sent a message to you and you sent message to me, and so far so good...
But when I enter in the chat from the android app the client show me the request to chat (saying that the encryption key was wrong).

From the desktop app:
![daniele_desktop](https://cloud.githubusercontent.com/assets/11871250/8694778/916970a6-2ae1-11e5-86e2-eef48ab0a80e.PNG)

From the android app:
![screenshot_2015-07-15-10-51-55](https://cloud.githubusercontent.com/assets/11871250/8694979/c3f5039a-2ae2-11e5-90b3-eae10eba876f.png)

**Comment by abika** [comment]
yes, that's the current intended behaviour, have to think about this...

**Comment by abika** [comment]
I have still no clue what to do here. Ok the user should see a least a warning when the key changes, but the option to refuse the new key seems useless...

**Comment by daniele-athome** [comment]
@abika if you click the reject button (actually "block") it unsubscribes from the user and blocks it. Why do you think it's useless?

**Comment by abika** [comment]
oh ok, sorry. I thought only the new key is just ignored. But that behaviour clearly makes sense.

Will the Android client recognize it if the Destop client does the same?

**Comment by daniele-athome** [comment]
It should: the blacklist is per-user.

**Comment by abika** [comment]
quick question here: why unsubscribing? When the contact is blocked no presence stanzas are received for this contact anymore, so isn't blocking enough?

**Comment by daniele-athome** [comment]
I thought removing it from the roster entirely would be more "complete" (you are indeed blocking a person and you don't want to see him/her again :-)

**Comment by abika** [comment]
okay, but I think only blocking is more appropriate here: Most of the time a key change occurs the reason is legitimate, and if the user is really unsure about it blocking is enough to prevent insecure communication but makes it easier to reestablish communication maybe after the key was verified using some other channel. (Key change-> I'm unsure & block -> call the contact: ok, not the CIA -> unblock)

Thus the Desktop client will only block

**Comment by daniele-athome** [comment]
You're right. I will align the Android app.
