### ISSUE TITLE
cannot add contacts 

### ISSUE THREAD

**Issue by syamgk** [kontalk/desktopclient-java#44]
there is no option to add contacts on desktop-client.

**Comment by daniele-athome** [comment]
Would you mind adding some description please?

**Comment by syamgk** [comment]
No, there is no option even for adding kontalk users on desktop-client.

**Comment by abika** [comment]
I added the ability to add Jabber user (by JID) with d279fe01ad8c5f0114ad17a0b204ff8c2e640e84. Adding Kontalk user by phone number will follow.

In a first test interoperability with standard XMPP/Jabber worked quite well. @daniele-athome do you have any concerns over adding arbitrary Jabber user? Its your server...

**Comment by daniele-athome** [comment]
Absolutely, no concerns for the server. It's a standard XMPP server federated with the Jabber network.
It's the Android client that is not yet ready for it :-)
