### ISSUE TITLE
No option to remove contacts 

### ISSUE THREAD

**Issue by syamgk** [kontalk/desktopclient-java#47]
there is no option to remove contacts on desktop-client.

**Comment by abika** [comment]
already working on it.

You're using the repository version, I assume?

**Comment by syamgk** [comment]
I am using it from 
$git clone  https://github.com/kontalk/desktopclient-java
is there any other repository for desktop-client ?

**Comment by abika** [comment]
No, I was just saying you're not using a release version of the code.

**Comment by syamgk** [comment]
@abika can you tag v3.0.2 ?
the latest master branch contains add/remove contact which is not available on previous release v3.0.1

**Comment by abika** [comment]
3.0.2 is not finished, yet. Release is in a couple of days...

**Comment by abika** [comment]
https://github.com/kontalk/desktopclient-java/releases/tag/v3.0.2
