### ISSUE TITLE
compress pictures bevor sending

### ISSUE THREAD

**Issue by webratte** [kontalk/desktopclient-java#53]
You should compress pictures (like Androidapp) bevor sending because most receivers will use a mobilephone with slower connection then DSL.

**Comment by abika** [comment]
what do mean? Compressing a jpeg image is pointless, it is already compressed.

I don't want do reduce the image quality either. First, by which parameter (percent/max. size)? And second, altering user files is bad habit.

Anyway, if the phone is connected by wifi you have cable speed. The desktop app can't predict that.

**Comment by daniele-athome** [comment]
@webratte is expressing his concern because the Android app has a *resize image* feature which reduces the file size (editable through a preference of course). He thinks it could be useful to have the same setting in the desktop app.

**Comment by webratte** [comment]
@daniele-athome That's what I mean :-)

**Comment by abika** [comment]
ah, ok. Didn't see that. So, an option to set the max. image size.

`TODO_LIST.add(set_max_img_size())`
