### ISSUE TITLE
Chinese characters in UI not shown correctly

### ISSUE THREAD

**Issue by abika** [kontalk/desktopclient-java#56]
... as reported by a user.

**Comment by Josh4all** [comment]
![2015-11-11_00-03-44](https://cloud.githubusercontent.com/assets/13466085/11083860/41c4bf7e-886f-11e5-83d3-7af1182c628f.png)
As shown above

**Comment by abika** [comment]
(question again) There is currently no Chinese translation for the desktop client user
interface. Did you create on yourself? If so, plz make the translation on Weblate so
others can benefit from it - and I can test it.

**Comment by abika** [comment]
This is a problem with your OS environment: The Chinese fonts are missing (or Java can't find them) . What OS are you using? For me it was fixed by installing `opendesktop-fonts` (on Arch Linux).

But there is another problem (maybe): Java is converting "zh_Hans" to "zh_hans", so the translation file won't be found. Please test the current master, if it doesn't work for you I'll have to find a solution here.

**Comment by Josh4all** [comment]
Looks like the characters show well under Ubuntu Mate, but not on Windows 10. Also now met another problem that I can't sign into my Kontalk acc with error prompt "Can't connect to server && Connection to server closed on error" :(

**Comment by abika** [comment]
don't know about Windows 10, I guess you have to install an extra Asia font package.

About the connection error: please create a new issue and post at least the exceptions from the log file (https://github.com/kontalk/desktopclient-java/wiki#i-found-a-bug-what-to-do)

**Comment by Josh4all** [comment]
Well, I guess I have no need to install any other Asian Fonts as Win10 itself is already in Simplified Chinese. I still couldn't get it working properly under Windows. :( Also, according to the console output, it shows it needs a translation file named "strings_zh.properties" instead of “strings_zh_Hans.properties”.

**Comment by abika** [comment]
I renamed the Chinese translation in master. At least it should be used now
