### ISSUE TITLE
can receive but not send messages

### ISSUE THREAD

**Issue by maxlinux2000** [kontalk/desktopclient-java#59]
HI

I don't know if I'm missing something but, today I compiled the desktopclient-java, and it work's apparently.

After import the key generated from the android client my contacts appears in the list of java client.
But if I send a message, the android client of my wife, I cant' receive it in java client.
If my wife send me a message, I receive it in both of client (android and java).

This is a bug or it's my fault?

Another question:
How to compile the java client in order to obtain the desktopclientjava.jar file?
actually I can run the java client with ./gradlew run but no client .jar file is created.

**Comment by abika** [comment]
The message history is not synchronized between clients, see #21.

> How to compile the java client in order to obtain the desktopclientjava.jar file?

Run `./gradlew build` . The jar will be created in the `./dist` folder.
