### ISSUE TITLE
Rename contacts' displayed name

### ISSUE THREAD

**Issue by breversa** [kontalk/desktopclient-java#60]
Feature request : being able to change a contact's diplayed name.

Useful to keep that list tidy when your contacts aren't. :-)

**Comment by abika** [comment]
Select a contact from the contact list, click on the display name and change it (?!)

**Comment by breversa** [comment]
Damn, that was is ? I tried right-clicking on the contact's name in the list, pressing F2… and since the nickname in "Contact's details" seemed to be a fixed field, I never thought of clicking on it. Maybe changing the field type to "editable" would solve this UI issue. :-)

**Comment by abika** [comment]
Youre probably not the only one who missed this. I already thought about adding an "edit" icon to the text fields as visual indication the values can be changed. Hope, thats enough.

**Comment by breversa** [comment]
Or maybe a standard "click to select then F2 or right-click to rename" ?

2015-12-10 20:02 GMT+01:00 Alex <notifications@github.com>:

**Comment by webratte** [comment]
Why not just extend the context menu by right click?
currently there are:
-block contact
-delete contact

now you can add 
-rename contact

and in future version you can also add stuff like:
-add to group 
and so on. 

I think this is very user friendly and intuitive.

**Comment by breversa** [comment]
That's actually what I tought about (and tried) too !

**Comment by abika** [comment]
I addressed this with three change:
* name and JID fields in the contact details got an 'edit' icon to indicate those values can be changed
* an 'edit contact' option was added to the side chat lists right click menu as a quick way to open the contact details for the chats contact
* pressing F2 with a chat or contact selected in the side lists now opens the corresponding contact details and the name field is focused

Changing the contact name directly in the side list is a bad choice imo - all edit options should bundled in the contact details. But those changes should be more than enough.

**Comment by breversa** [comment]
Sweet ! I'll try and test this ASAP. Thanks ! :-)

2016-01-18 17:00 GMT+01:00 Alex <notifications@github.com>:
