### ISSUE TITLE
Impossible to send picture

### ISSUE THREAD

**Issue by webratte** [kontalk/desktopclient-java#66]
If I tries to send a picture (44 kb) I get the message : "Upload of message failed"

Kontalktversion 3.0.4
OS: Linux

@abika If you need a log, please let me know how to get it.

**Comment by daniele-athome** [comment]
You can find help here on where to find the log: https://github.com/kontalk/desktopclient-java/wiki#i-found-a-bug-what-to-do
Thanks!

**Comment by abika** [comment]
thanks for reporting. But this must be some incompatibility problem with the older file upload service and its already obsolete with support for the new one (already in master).

Next version with the fix will soon be released...
