### ISSUE TITLE
Hide blocked users

### ISSUE THREAD

**Issue by webratte** [kontalk/desktopclient-java#67]
Implement a option to hide/show blocked users (like in Androidclient).

It helps to keep the contact list clean.

**Comment by abika** [comment]
don't know why you should have many blocked contacts. But done anyway

**Comment by webratte** [comment]
Hehhh, think in future ;-P
        
        Kontalk uses phonenumbers. And I'm sure my number is in many
        adress books. And if Kontalk sometimes more famous like WhatApp,
        there are will be users I don't like in contactlist :-)
        
        Thanks anyway
        
      
    On 08.05.2016 20:46, Alex wrote:
    
    
      don't know why you should have many blocked contacts. But done
        anyway
      —
        You are receiving this because you authored the thread.
        Reply to this email directly or view
          it on GitHub
