### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by jluttine** [kontalk/desktopclient-java#7]
I just cloned the repository but I have no idea how to build/install/run the client. I tried searching for instructions but couldn't find any. I'd suggest adding some instructions to readme or adding some other file with simple instructions, and/or adding some guidance here.

**Comment by abika** [comment]
It's quite simple but I [wrote that down](https://github.com/kontalk/desktopclient-java/wiki) anyway (and added Ant as build dep.)

**Comment by jluttine** [comment]
Thanks!
