### ISSUE TITLE
Error when trying to build from source: Could not find tools.jar

### ISSUE THREAD

**Issue by 10111011** [kontalk/desktopclient-java#70]
Hello, 
I'm trying to build from source:

I followed the build instructions on the Wiki page:

1. `git clone git@github.com:kontalk/desktopclient-java.git`
2. `cd desktopclient-java/`
3. `git submodule update --init`
4. `./gradlew run`

Output of the last command:
```

:client-common-java:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':client-common-java:compileJava'.
> Could not find tools.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.253 secs
```

`java -version`:
```

openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-0ubuntu4~16.04.1-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)
```

System used: Ubuntu 16.04 LTS

Can someone help please? Could this be a problem related to openjdk?

**Comment by abika** [comment]
Gradle can't find your Java installation, try something like
```sudo update-alternatives --config java```
or lookup how to do that for Ubuntu.

>Could this be a problem related to openjdk?

Nope. Using that myself.

**Comment by 10111011** [comment]
Thanks! it's working now
