### ISSUE TITLE
Text field looses focus

### ISSUE THREAD

**Issue by Buranek** [kontalk/desktopclient-java#75]
There are 3 problems with text field:

1. It forgets size;
2. It looses focus (2 variants: either switches to search or looses completely);
3. No dialogue (copy, cut) when pressing right button.

**Comment by abika** [comment]
Please check if the focus lost is completely fixed

**Comment by Buranek** [comment]
How can I check it? Previous version was released on 23 May. I can't see the new release.

**Comment by abika** [comment]
In case you can build from source. Otherwise please wait for a new release.

**Comment by Buranek** [comment]
Please give me instructions to build it.

**Comment by abika** [comment]
see here: https://github.com/kontalk/desktopclient-java/wiki#how-can-i-compile-the-code

**Comment by arielenter** [comment]
I was having the same problem with 3.1.1 - Polishing. I compiled the newest master and I can confirm that the problem is gone. Thank you so much :+1:
