### ISSUE TITLE
Bad background

### ISSUE THREAD

**Issue by Buranek** [kontalk/desktopclient-java#78]
Default background looks bad and it's not quite easy to read text when such background is active. Please include my background as default.
![graphite](https://cloud.githubusercontent.com/assets/6697344/18288494/481a231c-7484-11e6-8b89-b7354605d8c2.jpg)

**Comment by abika** [comment]
Yes, the whole GUI doesn't look that good. But the current background is plain and fits to the design. Sorry, but your background doesn't improve it. But you can easily set it as default background in the preferences.
