### ISSUE TITLE
Messages are initially not displayed correctly

### ISSUE THREAD

**Issue by Buranek** [kontalk/desktopclient-java#80]
Sometimes this bug accures: when sending or receiving message a part of it looses. And appears many seconds later. Bug applies to my messages and to contact messages.

**Comment by abika** [comment]
There is still a problem with updating the row height in the message list. Only one on row is visible and longer text is cut out. It is fixed after another rendering attempt e.g. when you move the mouse over the message list. I already worked on this for a long time and forgot about it. Will do another try...

Notice that only displaying a message affected, no message text or content is lost
