### ISSUE TITLE
Update notification on systray

### ISSUE THREAD

**Issue by webratte** [kontalk/desktopclient-java#83]
Kontalk: V 3.1.1
OS: Linux

After starting the desktopclient the systray icon is red in the left corner (new message) without new message is received.

**Comment by abika** [comment]
never had this problem. Every time you open the desktop client?
My guess: its a message sent to yourself and the chat is hidden?

**Comment by webratte** [comment]
Yes. This is happens on every time I start the desktop client.
What I have tried:
In all this situations there is no unread messages!
And this happens no matter if the window expanded or minimized to systray.
  
-start PC then start the client (the icon shows red corner)
-send myself a message and read this message (the icon shows blue/green(?) corner)
-close the client
-restart the client (the icon shows red corner)

Current settings of the client:
-show myself in contacts
-closed to systray

If you help me, maybe I can offer you a log.

**Comment by abika** [comment]
Still can't reproduce this, not with master or 3.1.1.

The log is only useful if it contains warnings or exceptions. Can you check that plz?

**Comment by webratte** [comment]
There are no warnings or somthing else is shown.
Maybe I will trie a reinstall.
I will Report if I have news.

**Comment by webratte** [comment]
How to deinstall on linux?
Delete the client folder seems not enough.
I would like to install the desktop client from the scratch. Delete Database?

**Comment by daniele-athome** [comment]
Delete the `~/.kontalk` folder. This will also delete your personal key and you'll have to reimport it (and all other settings as a matter of fact).

If you'd like to clean the build directory too, just run the "clean" command along with "run":

```
./gradlew clean run
```

**Comment by abika** [comment]
Just rename the database file `/home/[user dir]/.kontalk/kontalk_db.sqlite`. This is the safest way and should work fine.
If you really wanna start from scratch, rename the `.kontalk` directory

**Comment by webratte** [comment]
@abika you are too late. I have just deleted the .kontalk folder and reimported the key. ;-)

At the moment it seems to work. After starting the the client the systray icon shows not the red corner. Still I will do some tests and report later.

Thank you and @daniele-athome

**Comment by webratte** [comment]
Now it works fine for me.
If you like you can close this issue.

**Comment by abika** [comment]
Always feeling uncomfortable leaving something unresolved. Just re-open if it happens again.
