### ISSUE TITLE
Update contact list if user left Kontalk

### ISSUE THREAD

**Issue by webratte** [kontalk/desktopclient-java#84]
Kontalk: V 3.1.1
OS: Linux

A friend left Kontalk (deleted account) more then a month ago.
In Android client he disappeared from contact list automatically.

In Desktop client it should work the same way but he is still shown.

**Comment by daniele-athome** [comment]
Android OS schedules sync operations to run periodically, but on a desktop system there is no such mechanism. It would have to be implemented.

**Comment by webratte** [comment]
I think for the start it would be enough to check the list on start of the client if this is easyer to implement then a periodically check.

**Comment by daniele-athome** [comment]
Well the sync operation itself is quite heavy for server resources so the less you request it the better :-)
Although there are other mechanisms to check per-contact which are not so heavy. @abika for example last seen iq should respond with user not found IIRC.

**Comment by abika** [comment]
Removing a user remotely is simply not implement yet. My (preliminary) plan:
* detect if contact is missing in the roster
* ask for "last seen" iq and see if its not found
* ask user in dialog if contact should be removed

**Comment by webratte** [comment]
> ask user in dialog if contact should be removed

Is there a good reason to ask?
If he/she left Kontalk I think it's not needed in contact list I think.
