### ISSUE TITLE
Adapt UI to Android material/Android client design

### ISSUE THREAD

**Issue by abika** [kontalk/desktopclient-java#85]
- [x] update icons from Android client (somebody know where i can get the "menu" icon (these three dots)?)
- [x] <strike>use Android fonts (if there are not license issues)</strike>
- [x] imitate material design: solid colors, no borders
- [x] steal background image from Android client
- [x] imitate floating button in side list views

More?

**Comment by daniele-athome** [comment]
> somebody know where i can get the "menu" icon (these three dots)?

https://design.google.com/icons/#ic_more_vert

> use Android fonts (if there are not license issues)

It is not strictly necessary to use Android fonts, so if you find license issues, it's not a big deal.

> imitate material design: solid colors, no borders

I guess you already know your way around the Kontalk app resource files, especially colors.xml. If you need help just ask.

What about chat balloons? Do you intend to port all the themes too?

**Comment by abika** [comment]
> https://design.google.com/icons/#ic_more_vert

Thanks! Too hard to find:)

> What about chat balloons? Do you intend to port all the themes too?

No way. Its virtually impossible to port the Android themes to Swing. All I can do is set the component properties to look *like* Android

**Comment by daniele-athome** [comment]
> All I can do is set the component properties to look like Android 

Fine by me :-)

**Comment by webratte** [comment]
My personally chat balloon favourite would be the Hangouts theme like @relan offered for the current Alpha Adroid client.

Of course only if it's not to hard to imitate and implement.

**Comment by abika** [comment]
> My personally chat balloon favourite would be the Hangouts theme like @relan offered for the current Alpha Adroid client.

Sorry, not possible. The UI framework is totally different and doesn't support images for painting components.

**Comment by webratte** [comment]
I mean (if possible) show avatar beside chatballoon (no matter if it a square or what else) and 

"continuation" balloons for sequential messages. 
(This is more importent then the avatars beside the chatballoons ;-)) 
You know what I mean?!

**Comment by abika** [comment]
Yes, i get what you mean.
Avatars in the chat view are imo only useful for group chats. They take a lot of space in provide no additional information. @daniele-athome what is your opinion?
Changing the display of "continues" messages can always be done. I think for single chats only the gap between messages will be smaller.
Time for new issues...

**Comment by abika** [comment]
I tested using the Android font ("Roboto") but it doesn't really look good. It just don't "fit" with the desktop environment; all applications are using (almost) the same font, and Roboto looks very different. And I guess the font is optimized for different screen sizes.

**Comment by daniele-athome** [comment]
> Avatars in the chat view are imo only useful for group chats. They take a lot of space in provide no additional information. @daniele-athome what is your opinion?

In the spirit of consistent UI (between single and group chat) I'd say let's include avatars also in single chats. It also helps clearly stating whether the message is outgoing or incoming (I recently had a query about a user that couldn't tell when using an avatar-less theme), although that can be deducted by the presence of the status icon (but it's not so obvious anyway).
About the space needed: it doesn't need to be big. @abika if you think it's really wasted space (opposed to the actual usefulness of it), you can omit it in single chats. I'll leave the decision to you.

> I tested using the Android font ("Roboto") but it doesn't really look good.

IMHO we should follow platform rules and fonts (although I don't remember if Java/Swing uses the operating system default font or it has its own).

**Comment by daniele-athome** [comment]
> I recently had a query about a user that couldn't tell when using an avatar-less theme

Just to clarify: he opened Kontalk after some time and he didn't remember the conversation so when he opened the chat he couldn't tell who's who... I know, borderline case :-)

**Comment by webratte** [comment]
I think it's not important to make it exactly like Android. 
As I said "look and feel like Androidclient" I meand more things like:
-Separet messages with date 
-Sendet time inside the Chatballoons 

Informationen in the same place in both clients. 
So users can use it intuitiv. 
(nearly) no matter how it looks ;-)

**Comment by abika** [comment]
@daniele-athome 
> Just to clarify: he opened Kontalk after some time and he didn't remember the conversation so when he opened the chat he couldn't tell who's who... I know, borderline case :-)

No, I totally know what you mean and I agree that this is important. But for this reason all own messages in the desktop client are in a different color (and not white). On Android "Hangout" does this, "Silence" does not. (Besides that I really like "Silence", too bad chat balloons can't be used with Swing.)

@webratte 
> As I said "look and feel like Androidclient" I meand more things like:

Please just create issues for this. Like I said, there are a lot of thinks which can be improved, I will just need some time (and your good ideas:).

**Comment by webratte** [comment]
Just release a version with the current changes.
So I can test it and open issues for things I think thats needed ;-)

**Comment by abika** [comment]
https://github.com/kontalk/desktopclient-java/releases/tag/v3.1.2-beta

**Comment by abika** [comment]
everything - more or less - done. For more suggestions please open additional issues.
