### ISSUE TITLE
Feature request: Automatically check for client update

### ISSUE THREAD

**Issue by webratte** [kontalk/desktopclient-java#86]
May be a option "check also for beta versions".

If there no practical way for automatically check you could a Help menu item "check for updates".
Or much easier a simple Help menu item with target:
https://github.com/kontalk/desktopclient-java/releases

But this is definitely a issue with low priority :-)

**Comment by abika** [comment]
A simple link to the release page must be enough for now. Automatic version checking is supported with GitHub but needs definitely some work. And there is soo much more to do...

BTW GitHub has in-build RSS support. You can subscribe to https://github.com/kontalk/desktopclient-java/releases.atom for new releases.

**Comment by webratte** [comment]
> BTW GitHub has in-build RSS support. You can subscribe to https://github.com/kontalk/desktopclient-java/releases.atom for new releases.

This issue is not opened for me. I follow you on Github. ;-D
I opened it for users they ONLY use Kontalk.

But why not add this info about the RSS feed into the Help menu:

"To get always the newest Kontalk version subscribe to our [RSS Feed](https://github.com/kontalk/desktopclient-java/releases.atom)"

Or someting like this.

It's have to be as easy as possible to get the newest version. Users who work with outdated versions will be dissatisfied and will bad rate Kontalk.
