### ISSUE TITLE
Inform about new messages if chat open and minimized to Systray

### ISSUE THREAD

**Issue by webratte** [kontalk/desktopclient-java#92]
If I send a message to Alice an minimized to Systray (without leaving the current chat) and Alice answering while Kontalk is minimized to Systray --  the Systray Icon doesn’t change the colour.

If I turned off the sound on my PC I can't notice there is a new message from Alice.

**Comment by abika** [comment]
Does this always happen? And what was your OS, Ubuntu? Which DE?

**Comment by webratte** [comment]
Ups Sorry

OS: Linux
Kontalk: 3.1.1

It always happens if I receive a message in the current open chat (if minimized to systray too)
If chat with Alice is open before I minimize to systray an Bob sends me a message, this message change the colour of the systray icon.

**Comment by abika** [comment]
And the desktop environment (Unitiy, Gnome, KDE...)? It is working for me and I think the problem is that the tray icon is not repainted after it actually changed. System independent tray implementations are error-prone, I already had to deal with multiple bugs with Qt's tray icon in different environments.

**Comment by webratte** [comment]
The DE is LXDE (Lubuntu)

**Comment by abika** [comment]
oh sorry, I totally misread your report. There was a bug in my code and it is fixed now. You will always get a notification now if the the application window is not focused (sound and tray).

**Comment by webratte** [comment]
I think your misread is related to my bad english :-D
