### ISSUE TITLE
Seprate messages via date

### ISSUE THREAD

**Issue by webratte** [kontalk/desktopclient-java#94]
See for example the attached screenshot of the Android client.
In the desktop client is more space then in android client. Maybe also with year ?!

I personally like to use the completely date (dd.month.yyyy) ;-)

![screenshot_2015-08-30-12-03-22](https://cloud.githubusercontent.com/assets/6864851/19617246/23301a0e-982c-11e6-8659-16485334f90f.png)

**Comment by abika** [comment]
Screenshot:
![kon_date_separator2](https://cloud.githubusercontent.com/assets/1074117/20767994/8a3975f4-b73c-11e6-8731-11938d056c2d.png)

Year is only included if its not the current year.
Because I hope you know which year we have.)
