### ISSUE TITLE
Use not only tooltip for "last message"

### ISSUE THREAD

**Issue by webratte** [kontalk/desktopclient-java#95]
The tooltip on mouse over is great for additional information (exact date and time).

But if you add the string "last message" permanently it's clearer what "9 houres ago" means Ithink.

I think there is space enough.

Sometimes a picture say more then bad english. ;-)
So I attached a screenshot with what I mean.

![screenshot](https://cloud.githubusercontent.com/assets/6864851/19617376/5df416ce-982f-11e6-8862-57687ff9e6f0.gif)

**Comment by abika** [comment]
Sorry, this wont look good. First, its not guaranteed that there is enough space (it depends on the translation). And second, the string "Last message" will be repeated for every chat:
```
Alice
last message: 1 week ago
Bob
last message: 3 week ago
Charles
last message: 4 week ago
...
```
This is really ugly.

**Comment by webratte** [comment]
> This is really ugly.

I think not more then a information what seams not make sense, because I can't see what was 1 week ago until I go by chance over it with mouse arrow....

So I think you should find a better way or remove this information completely.
This info is already shown in last message and not needed a second time.
Isn't it?

**Comment by abika** [comment]
The same information is seen in the Android client, only with a date information. And WhatsApp and other messenger have exactly the same. I think most users will know what it means.

**Comment by d9h02f** [comment]
Why would 'last message' be necessary? What else do you think "2 hours ago" "5 days ago" etc could mean?

**Comment by webratte** [comment]
I don't know. Last seen? Last online?
There is no info about this time.

Maybe I'm a stupid user. But I'm sure I'm not the only one....

I also don't know why we need this info twice (one time in chat list and
one time in chatballoon).

And were in Androidclient is this info? I still can find it.

The more I thint about it the more I think this info is not needed in
chat list. Maybe it can be droped?!

**Comment by d9h02f** [comment]
Well, the content of the last message should probably be shown below the contact name in the list of conversations, that way I think there can't be any confusion, and it would look much better, too.

**Comment by webratte** [comment]
@d9h02f
Now as I read your Post I found it in the Androidclient. 
And there is it exactly so you write.
And this way it's intuitve that's why I couldn't find it :-) 
There is nothing uncertainties.

Thank you

**Comment by abika** [comment]
The problem is that there is not enough space. It sounds like a paradox but on Android the chat list can be much wider than in the desktop client.
Let's say the phone display width is very small: 480 pixel. The chat list covers the whole screen from left to right so its width is also 480px. On a desktop computer with small screen (1024x768px) the same list would cover almost half of the screen - only for the side panel, the actual chat is displayed next to it on the right side!

And for this smaller space there is too much information: chat icon, chat title/contact name, "last seen" date and "last message" text. So I omitted the "last message" text, it takes most space and is imo not that important.

**Comment by webratte** [comment]
OK, that sounds logical.

Still the last message time without no Info what it means is confusing me.

We should think about a better solution.

In Android client there is a.clear context because the last message time is shown beside the last message.

In Desktop client the last message time is shown beside the contact.

I will think about it.
Maybe I have a idea.

And don't forget:
You think more like a good dev.
I think only like a User ;-)

**Comment by d9h02f** [comment]
@abika, Signal Desktop manages just fine with limited space, see https://chrome.google.com/webstore/detail/signal-private-messenger/bikioccmkafdpakkkcpdbppfkghcmihk

**Comment by webratte** [comment]
Just a stupid (?) idea.

What think you about a chat list just in Android client?
Not splittet like in current Desktop client.

There is always only one chat opend.

And you could save space and could show the same Infos like in Android client. 

Think well about it before you will answere.

BTW: The UI would be more similar to Android client.

**Comment by d9h02f** [comment]
I also agree with @webratte that there is no need to split between contacts and conversations, again see Signal Desktop's design where all contacts are visible and they're sorted in order of who you last talked to.

**Comment by webratte** [comment]
But in the contact list is a other information '(last seen).
I never would write this issue if I was not confused.

OK, I never used WhatsApp.

And were in Android client is the information "last message"?
I ca't find it....

**Comment by webratte** [comment]
I don't know.

I also don't know why we need this info twice (one time in chat list and
one time in chatballoon).

And were in Androidclient is this info? I still can find it.

The more I thint about it the more I think this info is not needed in
chat list. Maybe you can drop it.

**Comment by d9h02f** [comment]
@webratte that's my point, a contact list is useless if you can just combine the contacts and the conversations.

**Comment by abika** [comment]
> Still the last message time without no Info what it means is confusing me.
> We should think about a better solution.

How about the "Last Message:" text only for the currently selected chat?

>  @abika, Signal Desktop manages just fine with limited space, see https://chrome.google.com/webstore/detail/signal-private-messenger/bikioccmkafdpakkkcpdbppfkghcmihk

The list is again much wider in Signal Desktop (and most of the space is not used if there is no chat with the contact). I don't want to use that much space.

> @webratte that's my point, a contact list is useless if you can just combine the contacts and the conversations.

Sorry, I don't like combining all chats (single and group chats) and contacts in one list. It always shows contacts I totally don't care about, combines two different sorting methods which is confusing and in Jabber/XMPP this cannot be consistent by design cause there could be more than one "1-to-1" chat with a contact (called multiple "threads" with the same contact).

**Comment by d9h02f** [comment]
> in Jabber/XMPP this cannot be consistent by design cause there could be more than one "1-to-1" chat with a contact

Who does this?

**Comment by webratte** [comment]
> in Jabber/XMPP this cannot be consistent by design cause there could be more than one "1-to-1" 
> chat with a contact (called multiple "threads" with the same contact).

In this unbelievable strangely case we will get big problems with Android client. ;-)

> How about the "Last Message:" text only for the currently selected chat?

This could be a idea for start.

I still believe a UI similar to Android is the better solution.
because:

-Users know that from the Android client (and other IMs) and it's easyer to switch between this clients.
-most users who use modern IMs are not interestet in technical details like XMPP. They want a logical UI (to find not logical UI parts is my part as a simple user :-))
-I never belong of the case that somone have to parallel chats to one person (like @d9h02f say "Who does this?)

That's my last words in this issue.
I will concentrate to find bugs.

BTW: I use the Desktop client most times to test an help to make the UI user friendly and suitably for masses.
Like I said before: I think like a user and not all ideas are my. I also talk about this, with my (non tech) friends and family.
You can believe me. Things what seems absolutely clear for you, can be really unclear for simple users.

So the more similar both clients in UI the less confused users.
