### ISSUE TITLE
Use draft to add bugreport to GitHub

### ISSUE THREAD

**Issue by webratte** [kontalk/desktopclient-java#96]
like this I have stolen from https://github.com/k9mail/k-9/issues/new ;-)

I belive it's easier for users and devs if there a clear structure.

*****************************************************************************

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Environment
Kontalk version:

Operating System:

**Comment by abika** [comment]
Didn't know this is supported now. Thanks!

Added a compact version. Don't wanna ask too many useless questions.
