### ISSUE TITLE
Impossible to import personal key

### ISSUE THREAD

**Issue by webratte** [kontalk/desktopclient-java#97]
### Expected behavior
Import of key should work

### Actual behavior
Import fails with error "wrong password".
But the password is definitely correct 

### Steps to reproduce
1. open the client
2. click options -> settings -> account
3. click import new account an choose your personal key
4. enter your password 

And then I get the error message.

### Environment
Kontalk version: 
3.1.2-beta

Operating System:
Linux LXDE (Lubuntu)

**Comment by abika** [comment]
What is the version of the Android client the key was extracted from? Special characters in the password? Are there warning or exceptions in the log file?

**Comment by webratte** [comment]
Sorry, Idon't know the Version of Androidclient.

In the password is a #

In the Desktopclient bevore this current beta (At the moment I don't know the version number but you will I'm sure ;-) exactly this key worked fine.
I also have tried it with remove the .kontalk folder without success.

The logfile I will check later.

**Comment by webratte** [comment]
There are warnings in the log:

`WARNUNG: can't remove cryptography restrictions
java.lang.IllegalAccessException: Can not set static final boolean field javax.crypto.JceSecurity.isRestricted to java.lang.Boolean
	at sun.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:76)
	at sun.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:80)
	at sun.reflect.UnsafeQualifiedStaticBooleanFieldAccessorImpl.set(UnsafeQualifiedStaticBooleanFieldAccessorImpl.java:77)
	at java.lang.reflect.Field.set(Field.java:764)
	at org.kontalk.util.CryptoUtils.removeCryptographyRestrictions(CryptoUtils.java:64)
	at org.kontalk.Kontalk.start(Kontalk.java:129)
	at org.kontalk.Kontalk.main(Kontalk.java:209)`

**Comment by abika** [comment]
Ohohoh, great! Oracle changed the code for the cryptography restrictions - made the `isRestricted` field final - and shipped it with a last update. Such crap...

Not only the import wont work but login will also not be possible after installing the Java 8 update ("u111" or so). But StackOverflow already knows more and has a solution http://stackoverflow.com/a/38625821/6286694 

 Have to publish another release with this fix soon before more people are complaining.

Thanks for the report, as always!

**Comment by webratte** [comment]
Sorry, Idon't know the Version of Androidclient.
    In the password is a #
    In the Desktopclient bevore this current beta (At
      the moment I don't know the version number but you will I'm sure
      ;-) exactly this key worked fine.
      I also have tried it with remove the .kontalk folder without
      success.
      
      The logfile I will check later.

**Comment by webratte** [comment]
Sorry, Idon't know the Version of Androidclient.

In the password is a #

In the Desktopclient bevore this current beta (At the moment I don't know the version number but you will I'm sure ;-) exactly this key worked fine.
I also have tried it with remove the .kontalk folder without success.

The logfile I will check later.

**Comment by daniele-athome** [comment]
@webratte everything alright? A couple of answers came in but they seem like duplicate of a previous one.

**Comment by webratte** [comment]
Ups...

there was a problem with my mailclient.

It seems all not sended Mails now out :-o 

Sorry.
