### ISSUE TITLE
retry reconnecting timer?

### ISSUE THREAD

**Issue by arielenter** [kontalk/desktopclient-java#98]
Is there a way to set the desktop client so that if it fails to connect once it can automatically try to connect again later? Right now, once it fails, it doesn't seem to try again until I go to the menu.

I'm using GNU/Linux, is there a terminal command that I could run to make kontalk try again once it has been open, or should I just make a bash file that closes it and opens it back every so often if not connected?

Thank you :)

### Additional information
Kontalk Desktop version: 3.1.1 and newer
Operating System: GNU/Linux
Desktop Environment:  gnome fallback

**Comment by abika** [comment]
I guess you want an additional option in network settings: "auto-reconnected on connection loss". With some delay between re-connecting and maybe a counter limit for the amount of connection tries?

**Comment by arielenter** [comment]
Yes, exactly :), I just didn't know how to put it in words as awesome as you did XD.

Meanwhile, I was hopping to make a work around if there is a way to send the order to connect to the client through terminal, or maybe reopening it with a bash file. I was hopping to get it's status through it's window tittle, but it doesn't seem to change when connected or not, so I'm guessing that the only way would be it's "verbose" out put maybe?

Anyway, it's probably too much of a hassle to do it that way. So I'm guessing that asking for that option it's a better solution xD

**Comment by abika** [comment]
Interval between retry is 20secs. No retry limit.

**Comment by arielenter** [comment]
Thanks a lot :) :+1:
